name = "music-stack"
compatibility_date = "2026-07-03"
pages_build_output_dir = "."

[[d1_databases]]
binding = "LYRIC_LAB_DB"
database_name = "music-stack-lyric-lab"
database_id = "8ca9d7d1-701e-4edf-a4a6-3bf1a6b00821"
migrations_dir = "migrations"
